###
POST http://localhost:4000/api/users
Content-Type: application/json

{
    "name":"aldo",
    "email":"jose@test.com",
    "password":"password"
}

###
POST http://localhost:4000/api/login
Content-Type: application/json

{
    "email":"jose@test.com",
    "password":"password"
}
